services:
  spring-boot-app:
    image: anasortukov/chat-app-demo
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"
